// =============================================================================
// midi_player.ino
// MIDI-to-ESP32 Player — plays monophonic melodies via passive buzzer (PWM)
//
// Hardware:
//   - ESP32 (any variant)
//   - Passive buzzer on BUZZER_PIN
//   - Tactile button on BUTTON_PIN (external pull-down resistor required)
//
// Wiring:
//   Button  → GPIO 14  (+) | GND (−) | 10kΩ pull-down to GND
//   Buzzer  → GPIO 13  (+) | GND (−)
//
// Note: change BUZZER_PIN to 27 when using real hardware instead of simulator.
// =============================================================================

// ── Pin configuration ────────────────────────────────────────────────────────
#define BUTTON_PIN  14    // tactile button (external pull-down)
#define BUZZER_PIN  13    // passive buzzer (PWM output)
                          // → use pin 27 on physical hardware

// ── PWM configuration ────────────────────────────────────────────────────────
#define PWM_FREQ_INIT  1500   // initial PWM carrier frequency (Hz)
#define PWM_RESOLUTION    8   // PWM resolution in bits (0-255)

// ── Timing ───────────────────────────────────────────────────────────────────
#define NOTE_ON_RATIO   0.9f  // fraction of duration spent playing the note
#define NOTE_OFF_RATIO  0.1f  // fraction of duration used as inter-note gap
#define START_DELAY_MS  2000  // delay between button press and playback start

// ── State ────────────────────────────────────────────────────────────────────
bool active = false;

// =============================================================================
// playNote — emit a single tone via PWM
//   freq     : frequency in Hz  (0 = silence)
//   duration : total note duration in milliseconds
// =============================================================================
void playNote(int freq, int duration) {
  Serial.print("Note: ");
  Serial.print(freq);
  Serial.print(" Hz  |  duration: ");
  Serial.print(duration);
  Serial.println(" ms");

  ledcWriteTone(BUZZER_PIN, freq);
  delay((int)(duration * NOTE_ON_RATIO));

  ledcWriteTone(BUZZER_PIN, 0);        // brief silence between notes
  delay((int)(duration * NOTE_OFF_RATIO));
}

// =============================================================================
// playMusic — full melody sequence (auto-generated by midi_converter.ipynb)
// =============================================================================
void playMusic() {
  Serial.println("[Player] Playback started");

  playNote(659, 299);
  playNote(440, 150);
  playNote(494, 149);
  playNote(523, 150);
  playNote(587, 149);
  playNote(659, 299);
  playNote(740, 150);
  playNote(831, 149);
  playNote(880, 299);
  playNote(988, 300);
  playNote(1047, 299);
  playNote(440, 300);
  playNote(392, 600);
  playNote(988, 599);
  playNote(349, 299);
  playNote(880, 150);
  playNote(831, 149);
  playNote(880, 299);
  playNote(330, 300);
  playNote(294, 299);
  playNote(988, 299);
  playNote(831, 900);
  playNote(988, 149);
  playNote(880, 150);
  playNote(831, 149);
  playNote(698, 150);
  playNote(659, 150);
  playNote(587, 149);
  playNote(523, 150);
  playNote(587, 150);
  playNote(659, 150);
  playNote(523, 149);
  playNote(440, 300);
  playNote(1047, 150);
  playNote(988, 150);
  playNote(880, 149);
  playNote(784, 150);
  playNote(698, 150);
  playNote(659, 150);
  playNote(587, 150);
  playNote(659, 149);
  playNote(698, 150);
  playNote(587, 150);
  playNote(494, 300);
  playNote(1175, 149);
  playNote(1047, 150);
  playNote(988, 150);
  playNote(880, 150);
  playNote(784, 150);
  playNote(698, 149);
  playNote(659, 150);
  playNote(698, 150);
  playNote(784, 150);
  playNote(659, 150);
  playNote(523, 149);
  playNote(587, 150);
  playNote(659, 150);
  playNote(523, 150);
  playNote(698, 150);
  playNote(784, 149);
  playNote(880, 150);
  playNote(698, 150);
  playNote(587, 150);
  playNote(659, 150);
  playNote(698, 149);
  playNote(587, 150);
  playNote(494, 150);
  playNote(523, 150);
  playNote(587, 150);
  playNote(494, 149);
  playNote(659, 150);
  playNote(698, 150);
  playNote(784, 150);
  playNote(659, 150);
  playNote(523, 149);
  playNote(587, 150);
  playNote(659, 150);
  playNote(523, 150);
  playNote(440, 150);
  playNote(494, 149);
  playNote(523, 150);
  playNote(440, 149);
  playNote(587, 150);
  playNote(659, 149);
  playNote(698, 150);
  playNote(587, 149);
  playNote(494, 524);
  playNote(440, 75);
  playNote(494, 149);
  delay(150);
  playNote(392, 149);
  playNote(440, 149);
  playNote(494, 150);
  playNote(523, 149);
  playNote(587, 150);
  playNote(659, 149);
  playNote(698, 300);
  playNote(415, 149);
  playNote(440, 150);
  playNote(494, 299);
  playNote(587, 300);
  playNote(659, 150);
  playNote(587, 149);
  playNote(523, 149);
  playNote(494, 150);
  playNote(523, 149);
  playNote(494, 150);
  playNote(440, 149);
  playNote(659, 149);
  playNote(523, 150);
  playNote(494, 149);
  playNote(440, 150);
  playNote(659, 149);
  playNote(880, 149);
  playNote(831, 150);
  playNote(880, 149);
  playNote(523, 150);
  playNote(311, 149);
  playNote(523, 149);
  playNote(880, 150);
  playNote(880, 149);
  playNote(311, 150);
  playNote(523, 149);
  playNote(880, 149);
  playNote(880, 150);
  playNote(494, 149);
  playNote(880, 150);
  playNote(784, 149);
  playNote(740, 149);
  playNote(784, 150);
  playNote(740, 149);
  playNote(659, 150);
  playNote(988, 149);
  playNote(784, 149);
  playNote(740, 150);
  playNote(659, 149);
  playNote(988, 150);
  playNote(1047, 149);
  playNote(988, 149);
  playNote(1047, 150);
  playNote(659, 149);
  playNote(370, 150);
  playNote(587, 149);
  playNote(1047, 149);
  playNote(1047, 150);
  playNote(415, 149);
  playNote(587, 150);
  playNote(988, 149);
  playNote(587, 149);
  playNote(415, 150);
  playNote(587, 149);
  playNote(523, 150);
  playNote(494, 149);
  playNote(440, 149);
  playNote(494, 150);
  playNote(523, 149);
  playNote(659, 150);
  playNote(440, 149);
  playNote(494, 149);
  playNote(523, 150);
  playNote(659, 149);
  playNote(880, 150);
  playNote(988, 149);
  playNote(1047, 149);
  playNote(880, 150);
  playNote(1245, 899);
  playNote(440, 150);
  playNote(523, 149);
  playNote(494, 149);
  playNote(440, 150);
  playNote(392, 149);
  playNote(370, 150);
  playNote(392, 149);
  playNote(494, 149);
  playNote(659, 150);
  playNote(988, 149);
  playNote(880, 149);
  playNote(784, 149);
  playNote(740, 149);
  playNote(659, 150);
  playNote(784, 149);
  playNote(740, 149);
  playNote(659, 149);
  playNote(622, 150);
  playNote(659, 299);
  playNote(466, 149);
  playNote(494, 149);
  playNote(554, 300);
  playNote(659, 299);
  playNote(740, 149);
  playNote(659, 150);
  playNote(587, 149);
  playNote(554, 149);
  playNote(622, 300);
  playNote(740, 149);
  playNote(784, 149);
  playNote(880, 299);
  playNote(740, 300);
  playNote(659, 149);
  playNote(622, 149);
  playNote(554, 149);
  playNote(494, 150);
  playNote(440, 149);
  playNote(370, 149);
  playNote(392, 149);
  playNote(494, 149);
  playNote(659, 150);
  playNote(784, 149);
  playNote(988, 149);
  playNote(659, 149);
  playNote(494, 300);
  playNote(622, 299);
  playNote(659, 149);
  playNote(494, 149);
  playNote(523, 150);
  playNote(440, 149);
  playNote(392, 149);
  playNote(659, 149);
  playNote(370, 149);
  playNote(622, 150);
  playNote(330, 299);
  playNote(659, 299);
  playNote(440, 150);
  playNote(494, 149);
  playNote(523, 149);
  playNote(587, 149);
  playNote(659, 300);
  playNote(740, 149);
  playNote(831, 149);
  playNote(880, 299);
  playNote(988, 300);
  playNote(1047, 299);
  playNote(440, 300);
  playNote(392, 599);
  playNote(988, 600);
  playNote(349, 300);
  playNote(880, 149);
  playNote(831, 149);
  playNote(880, 299);
  playNote(330, 300);
  playNote(294, 299);
  playNote(988, 300);
  playNote(831, 899);
  playNote(988, 149);
  playNote(880, 149);
  playNote(831, 149);
  playNote(698, 150);
  playNote(659, 149);
  playNote(587, 149);
  playNote(523, 149);
  playNote(587, 149);
  playNote(659, 150);
  playNote(523, 149);
  playNote(440, 299);
  playNote(1047, 149);
  playNote(988, 150);
  playNote(880, 149);
  playNote(784, 149);
  playNote(698, 149);
  playNote(659, 149);
  playNote(587, 150);
  playNote(659, 149);
  playNote(698, 149);
  playNote(587, 149);
  playNote(494, 300);
  playNote(1175, 149);
  playNote(1047, 149);
  playNote(988, 149);
  playNote(880, 149);
  playNote(784, 150);
  playNote(698, 149);
  playNote(659, 149);
  playNote(698, 149);
  playNote(784, 149);
  playNote(659, 150);
  playNote(523, 149);
  playNote(587, 149);
  playNote(659, 149);
  playNote(523, 149);
  playNote(698, 150);
  playNote(784, 149);
  playNote(880, 149);
  playNote(698, 149);
  playNote(587, 149);
  playNote(659, 150);
  playNote(698, 149);
  playNote(587, 149);
  playNote(494, 149);
  playNote(523, 149);
  playNote(587, 150);
  playNote(494, 149);
  playNote(659, 149);
  playNote(698, 149);
  playNote(784, 149);
  playNote(659, 150);
  playNote(523, 149);
  playNote(587, 149);
  playNote(659, 149);
  playNote(523, 149);
  playNote(440, 150);
  playNote(494, 149);
  playNote(523, 149);
  playNote(440, 149);
  playNote(587, 149);
  playNote(659, 150);
  playNote(698, 149);
  playNote(587, 149);
  playNote(494, 524);
  playNote(440, 75);
  playNote(494, 149);
  delay(149);
  playNote(392, 149);
  playNote(440, 150);
  playNote(494, 149);
  playNote(523, 149);
  playNote(587, 149);
  playNote(659, 149);
  playNote(698, 300);
  playNote(415, 149);
  playNote(440, 149);
  playNote(494, 300);
  playNote(587, 299);
  playNote(659, 149);
  playNote(587, 149);
  playNote(523, 150);
  playNote(494, 149);
  playNote(523, 149);
  playNote(494, 149);
  playNote(440, 149);
  playNote(659, 150);
  playNote(523, 149);
  playNote(494, 149);
  playNote(440, 149);
  playNote(659, 149);
  playNote(880, 150);
  playNote(831, 149);
  playNote(880, 149);
  playNote(523, 149);
  playNote(311, 149);
  playNote(523, 150);
  playNote(880, 149);
  playNote(880, 149);
  playNote(311, 149);
  playNote(523, 149);
  playNote(880, 150);

  Serial.println("[Player] Playback complete");
}

// =============================================================================
// setup
// =============================================================================
void setup() {
  Serial.begin(115200);

  pinMode(BUTTON_PIN, INPUT);           // external pull-down resistor on board
  ledcAttach(BUZZER_PIN, PWM_FREQ_INIT, PWM_RESOLUTION);

  Serial.println("[System] Ready — press button to start playback");
}

// =============================================================================
// loop
// =============================================================================
void loop() {
  int state = digitalRead(BUTTON_PIN);

  // Uncomment to debug button state:
  // Serial.print("[Button] State: "); Serial.println(state);

  // Pull-down wiring: HIGH = button pressed
  if (state == HIGH && !active) {
    active = true;
    Serial.print("[Button] Pressed — starting in ");
    Serial.print(START_DELAY_MS / 1000);
    Serial.println(" s...");

    delay(START_DELAY_MS);
    playMusic();

    active = false;
  }

  delay(200);   // debounce / reduce serial spam
}
